services:
  halnet:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - OPENROUTER_API_KEY
      - AI_MODEL=openai/gpt-oss-20b:free
      - REDIS_URL=redis://redis:6379
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: halnet-redis
    networks:
      - my-network
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN
    networks:
      - my-network
    depends_on:
      - halnet
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
